# Generated by Django 3.0.2 on 2022-02-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_manage', '0004_auto_20220224_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='age_range',
            name='age',
            field=models.CharField(max_length=10),
        ),
    ]
