# Generated by Django 3.0.2 on 2022-02-24 13:03

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('post_manage', '0005_auto_20220224_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='age_range',
        ),
        migrations.AddField(
            model_name='post',
            name='age_range',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('15-20', -5), ('21-25', -5), ('26-30', -5), ('31-35', -5), ('36-40', -5), ('41-45', -5), ('46-50', -5), ('51-55', -5), ('56-60', -5)], max_length=53),
        ),
        migrations.DeleteModel(
            name='Age_range',
        ),
    ]
