# Generated by Django 3.0.2 on 2022-02-24 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_manage', '0007_auto_20220224_2230'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='salary',
            new_name='age',
        ),
    ]
