# Generated by Django 3.0.2 on 2022-02-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_manage', '0008_auto_20220224_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[('Employee', 'Employee'), ('Student', 'Student')], max_length=100, null=True),
        ),
    ]
