# Generated by Django 3.0.2 on 2022-02-24 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_manage', '0009_auto_20220225_0217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AddField(
            model_name='post',
            name='student',
            field=models.BooleanField(default=False),
        ),
    ]
