# Generated by Django 3.0.2 on 2022-02-24 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_manage', '0010_auto_20220225_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='student',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
